import React, { useEffect, useRef, useState } from 'react';
import { categories, pinSchema } from '../schemas';
import { Card, Icon, FormActions, useDraftEditor } from './primitives';
// Provider operations are injected; the reusable card owns no API client.
export function DestinationMap({ data, onAction, disabled, mapAdapter: MapAdapter, placeSearch, preview = true }) {
  const [selected, setSelected] = useState(null); const [filters, setFilters] = useState(Object.keys(categories)); const [draft, setDraft] = useState(null); const [error, setError] = useState('');
  const [placeQuery, setPlaceQuery] = useState(''); const [results, setResults] = useState([]); const [searching, setSearching] = useState(false);
  const searchVersion = useRef(0);
  useEffect(() => () => { searchVersion.current += 1; }, []);
  useDraftEditor(draft, onAction);
  async function search() {
    const version = ++searchVersion.current; setSearching(true); setError(''); setResults([]);
    try { const found = await placeSearch(placeQuery.trim(), data.destination); if (version === searchVersion.current) { setResults(found); if (!found.length) setError('No matching places. Try a more specific name.'); } }
    catch { if (version === searchVersion.current) setError('Place search is unavailable. Try again.'); }
    finally { if (version === searchVersion.current) setSearching(false); }
  }
  function cancel() { searchVersion.current += 1; setDraft(null); setResults([]); setSearching(false); }
  const visible = data.pins.filter(p => filters.includes(p.category));
  const pin = visible.find(p => p.id === selected);
  function inspect(id) { setSelected(id); onAction('inspect_place', { id }); }
  function save(e) { e.preventDefault(); const result = pinSchema.safeParse(draft); if (!result.success) { setError(result.error.issues[0].message); return; } onAction(data.pins.some(p => p.id === draft.id) ? 'edit_pin' : 'add_pin', result.data); setSelected(draft.id); setFilters(f => [...new Set([...f, draft.category])]); setDraft(null); }
  function add() { setError(''); setPlaceQuery(''); setResults([]); setDraft({ id: `pin-${Date.now()}`, name: '', category: 'activity', position: preview ? { lat: 38.716, lng: -9.14 } : null, description: '' }); }
  return <Card editableEmpty={!preview} title="Your places" eyebrow="A SENSE OF PLACE" icon="pin" data={data} onAction={onAction} className="ds-map-card" empty="A destination, a place to stay, a café worth finding. Your places will belong here." action={<button className="ds-button small" disabled={disabled || data.pins.length >= 50 || (!preview && !placeSearch)} onClick={add}><Icon name="plus" size={16}/> Add place</button>}>
    <div className="ds-map-summary"><strong>{data.destination || 'Destination not set'}</strong><span className="ds-tag">{data.final ? 'Destination chosen' : 'Exploring'}</span>{preview && data.destination && !data.final && <button className="ds-text-button" disabled={disabled} onClick={() => onAction('choose_destination', { name: data.destination })}>Choose destination</button>}</div>
    {MapAdapter ? <MapAdapter destination={data.destination} final={data.final} places={visible} selectedId={selected} onSelect={inspect}/> : <div className="ds-map-placeholder">Provide a map adapter to display these places.</div>}
    <div className="ds-map-legend" aria-label="Filter places by category">{Object.entries(categories).map(([key,c]) => <button key={key} style={{ '--category': c.color }} aria-pressed={filters.includes(key)} onClick={() => { const next = filters.includes(key) ? filters.filter(k => k !== key) : [...filters,key]; setFilters(next); onAction('filter_pins', { categories: next }); }}><i/>{c.label}</button>)}</div>
    {draft ? <form className="ds-form ds-pin-form" onSubmit={save}><h3>{data.pins.some(p => p.id === draft.id) ? 'Edit place' : preview ? 'Add a sample place' : 'Add a place'}</h3>{!preview && !data.pins.some(p => p.id === draft.id) && <div className="canvas-place-search"><label>Find a place<input value={placeQuery} onChange={e => { searchVersion.current += 1; setSearching(false); setResults([]); setPlaceQuery(e.target.value); setDraft({ ...draft, position: null }); }} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); if (placeQuery.trim().length >= 2) search(); } }}/></label><button type="button" className="ds-button small" disabled={searching || disabled || placeQuery.trim().length < 2} onClick={search}>Search places</button>{searching && <p role="status">Finding places…</p>}{results.map(result => <button type="button" className="canvas-place-result" key={result.id} onClick={() => { setDraft({ ...draft, name: result.name, position: result.position }); setResults([]); setError(''); }}><strong>{result.name}</strong><small>{result.address}</small></button>)}<small>Google Maps · select a result to place its pin.</small></div>}<div className="ds-form-grid"><label>Place name<input autoFocus required maxLength={120} placeholder="A café by the river" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/></label><label>Category<select value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}>{Object.entries(categories).map(([k,c]) => <option key={k} value={k}>{c.label}</option>)}</select></label></div><label>A little note<input maxLength={240} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })}/></label>{preview && <small>Sample position only. Place search connects later.</small>}{error && <p role="alert" className="ds-error">{error}</p>}<FormActions cancel={cancel} busy={disabled || (!preview && !draft.position)}/></form> : pin ? <div className="ds-pin-details" style={{ '--category': categories[pin.category].color }}><span className="ds-category-icon"><Icon name={categories[pin.category].icon}/></span><div><small>{categories[pin.category].label}</small><h3>{pin.name}</h3><p>{pin.description || 'A place to explore on your trip.'}</p><div className="ds-inline-actions"><button disabled={disabled} onClick={() => {setError('');setDraft({ ...pin });}}>Edit place</button><button disabled={disabled} onClick={() => { onAction('remove_pin', { id: pin.id }); setSelected(null); }}>Remove</button></div></div><button className="ds-icon-button" aria-label="Close place details" onClick={() => setSelected(null)}><Icon name="close" size={16}/></button></div> : <p className="ds-map-hint">{visible.length ? 'Choose a pin. Find a little more to look forward to.' : data.pins.length ? 'No places in these categories. Turn a category back on.' : preview ? 'No places yet. Add your first sample place.' : 'No places yet. Search for a place to add its pin.'}</p>}
    <details className="ds-place-list"><summary>All visible places <span>{visible.length}</span></summary><ul>{visible.map(p => <li key={p.id}><button aria-pressed={selected === p.id} onClick={() => inspect(p.id)}><Icon name={categories[p.category].icon} size={16}/>{p.name}<span>{categories[p.category].label}</span></button></li>)}</ul></details>
  </Card>;
}
