import React, { useState } from 'react';
import { categories, pinSchema } from '../schemas';
import { Card, Icon, FormActions } from './primitives';
// The real Google Maps adapter can be injected later. This component owns no SDK or API client.
export function DestinationMap({ data, onAction, disabled, mapAdapter: MapAdapter }) {
  const [selected, setSelected] = useState(null); const [filters, setFilters] = useState(Object.keys(categories)); const [draft, setDraft] = useState(null); const [error, setError] = useState('');
  const visible = data.pins.filter(p => filters.includes(p.category));
  const pin = visible.find(p => p.id === selected);
  function inspect(id) { setSelected(id); onAction('inspect_place', { id }); }
  function save(e) { e.preventDefault(); const result = pinSchema.safeParse(draft); if (!result.success) { setError(result.error.issues[0].message); return; } onAction(data.pins.some(p => p.id === draft.id) ? 'edit_pin' : 'add_pin', result.data); setSelected(draft.id); setFilters(f => [...new Set([...f, draft.category])]); setDraft(null); }
  function add() { setError(''); setDraft({ id: `pin-${Date.now()}`, name: '', category: 'activity', position: { lat: 38.716, lng: -9.14 }, description: '' }); }
  return <Card title="Your places" eyebrow="A SENSE OF PLACE" icon="pin" data={data} onAction={onAction} className="ds-map-card" empty="A destination, a place to stay, a café worth finding. Your places will belong here." action={<button className="ds-button small" disabled={disabled || data.pins.length >= 50} onClick={add}><Icon name="plus" size={16}/> Add place</button>}>
    <div className="ds-map-summary"><strong>{data.destination || 'Destination not set'}</strong><span className="ds-tag">{data.final ? 'Destination chosen' : 'Exploring'}</span>{data.destination && !data.final && <button className="ds-text-button" disabled={disabled} onClick={() => onAction('choose_destination', { name: data.destination })}>Choose destination</button>}</div>
    {MapAdapter ? <MapAdapter places={visible} selectedId={selected} onSelect={inspect}/> : <div className="ds-map-placeholder">Provide a map adapter to display these places.</div>}
    <div className="ds-map-legend" aria-label="Filter places by category">{Object.entries(categories).map(([key,c]) => <button key={key} style={{ '--category': c.color }} aria-pressed={filters.includes(key)} onClick={() => { const next = filters.includes(key) ? filters.filter(k => k !== key) : [...filters,key]; setFilters(next); onAction('filter_pins', { categories: next }); }}><i/>{c.label}</button>)}</div>
    {draft ? <form className="ds-form ds-pin-form" onSubmit={save}><h3>{data.pins.some(p => p.id === draft.id) ? 'Edit place' : 'Add a sample place'}</h3><div className="ds-form-grid"><label>Place name<input autoFocus required maxLength={120} placeholder="A café by the river" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/></label><label>Category<select value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}>{Object.entries(categories).map(([k,c]) => <option key={k} value={k}>{c.label}</option>)}</select></label></div><label>A little note<input maxLength={240} value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })}/></label><small>Sample position only. Place search connects later.</small>{error && <p role="alert" className="ds-error">{error}</p>}<FormActions cancel={() => setDraft(null)} busy={disabled}/></form> : pin ? <div className="ds-pin-details" style={{ '--category': categories[pin.category].color }}><span className="ds-category-icon"><Icon name={categories[pin.category].icon}/></span><div><small>{categories[pin.category].label}</small><h3>{pin.name}</h3><p>{pin.description || 'A place to explore on your trip.'}</p><div className="ds-inline-actions"><button disabled={disabled} onClick={() => {setError('');setDraft({ ...pin });}}>Edit place</button><button disabled={disabled} onClick={() => { onAction('remove_pin', { id: pin.id }); setSelected(null); }}>Remove</button></div></div><button className="ds-icon-button" aria-label="Close place details" onClick={() => setSelected(null)}><Icon name="close" size={16}/></button></div> : <p className="ds-map-hint">{visible.length ? 'Choose a pin. Find a little more to look forward to.' : data.pins.length ? 'No places in these categories. Turn a category back on.' : 'No places yet. Add your first sample place.'}</p>}
    <details className="ds-place-list"><summary>All visible places <span>{visible.length}</span></summary><ul>{visible.map(p => <li key={p.id}><button aria-pressed={selected === p.id} onClick={() => inspect(p.id)}><Icon name={categories[p.category].icon} size={16}/>{p.name}<span>{categories[p.category].label}</span></button></li>)}</ul></details>
  </Card>;
}
