import React, { useState } from 'react';
import { linkSchema } from '../schemas';
import { Card, Icon, FormActions, useDraftEditor } from './primitives';
export function ImportantLinks({ data, onAction, disabled, preview = true }) {
  const [draft, setDraft] = useState(null); const [error, setError] = useState('');
  useDraftEditor(draft, onAction);
  function save(e) { e.preventDefault(); const parsed = linkSchema.safeParse(draft); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } onAction(data.items.some(i => i.id === draft.id) ? 'edit_link' : 'add_link', parsed.data); setDraft(null); }
  return <Card editableEmpty={!preview} title="Worth keeping close" eyebrow="USEFUL WEBSITES" icon="link" className="ds-links" data={data} onAction={onAction} empty="A useful website is even better when you remember why you saved it." action={<button className="ds-icon-button" aria-label="Add website" disabled={disabled || data.items.length >= 20} onClick={() => {setError('');setDraft({ id: `link-${Date.now()}`, title: '', url: '', purpose: '', category: 'other' });}}><Icon name="plus" size={18}/></button>}>
    {!data.items.length && <p className="ds-muted">No websites yet.</p>}{data.items.map(item => <article className="ds-link-item" key={item.id}><a className="ds-link-open" href={item.url} target="_blank" rel="noopener noreferrer" onClick={preview ? e => { e.preventDefault(); onAction('open_link', { url: item.url }); } : undefined}><strong>{item.title}</strong><span>↗</span></a><small>{new URL(item.url).hostname.replace(/^www\./,'')}</small><p>{item.purpose}</p><button className="ds-text-button" aria-label={`Edit ${item.title}`} disabled={disabled} onClick={() => {setError('');setDraft({ ...item });}}>Edit website</button></article>)}
    {draft && <form className="ds-form" onSubmit={save}><label>Website title<input autoFocus required maxLength={120} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })}/></label><label>Website URL<input required maxLength={2048} placeholder="https://…" value={draft.url} onChange={e => setDraft({ ...draft, url: e.target.value })}/></label><label>Why keep it?<input maxLength={240} value={draft.purpose} onChange={e => setDraft({ ...draft, purpose: e.target.value })}/></label><label>Category<select value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}>{['official','transport','attraction','practical','other'].map(c => <option key={c}>{c}</option>)}</select></label>{error && <p role="alert" className="ds-error">{error}</p>}<FormActions cancel={() => setDraft(null)} busy={disabled}/>{data.items.some(i => i.id === draft.id) && <button type="button" className="ds-text-button danger" disabled={disabled} onClick={() => {onAction('remove_link', {id:draft.id});setDraft(null);}}>Remove website</button>}</form>}
  </Card>;
}
