import React, { useState } from 'react';
import { essentialsSchema } from '../schemas';
import { Card, Icon, EditButton, FormActions, useDraftEditor } from './primitives';
export function TripEssentials({ data, onAction, disabled, preview = true }) {
  const [draft, setDraft] = useState(null); const [error, setError] = useState('');
  useDraftEditor(draft, onAction);
  function save(e) { e.preventDefault(); const result = essentialsSchema.safeParse(draft); if (!result.success) { setError(result.error.issues[0].message); return; } onAction('edit_essentials', result.data); setDraft(null); setError(''); }
  const dates = data.dates.flexible ? data.dates.note || 'Flexible dates' : [data.dates.start, data.dates.end].filter(Boolean).join(' → ') || 'Not set';
  return <Card editableEmpty={!preview} title="Trip essentials" eyebrow="THE FOUNDATION" data={data} onAction={onAction} className="ds-essentials" action={<EditButton disabled={disabled} onClick={() => { setDraft(structuredClone(data)); setError(''); }}/>}>
    {draft ? <form onSubmit={save} className="ds-form"><div className="ds-form-grid"><label className="ds-check"><input type="checkbox" checked={draft.dates.flexible} onChange={e => setDraft({ ...draft, dates: { ...draft.dates, flexible: e.target.checked, start: '', end: '' } })}/>Flexible dates</label>{!draft.dates.flexible && <><label>Start date<input type="date" value={draft.dates.start} onChange={e => setDraft({ ...draft, dates: { ...draft.dates, start: e.target.value } })}/></label><label>End date<input type="date" value={draft.dates.end} onChange={e => setDraft({ ...draft, dates: { ...draft.dates, end: e.target.value } })}/></label></>}<label>Date note<input maxLength={200} value={draft.dates.note} onChange={e => setDraft({ ...draft, dates: { ...draft.dates, note: e.target.value } })}/></label><label>Travelers<input type="number" min="1" max="50" value={draft.travelers ?? ''} onChange={e => setDraft({ ...draft, travelers: e.target.value === '' ? null : Number(e.target.value) })}/></label><label className="ds-check"><input type="checkbox" checked={draft.budget.noFixedBudget} onChange={e => setDraft({ ...draft, budget: { label: '', noFixedBudget: e.target.checked } })}/>No fixed budget</label>{!draft.budget.noFixedBudget && <label>Budget<input maxLength={200} value={draft.budget.label} onChange={e => setDraft({ ...draft, budget: { ...draft.budget, label: e.target.value } })}/></label>}</div>{error && <p role="alert" className="ds-error">{error}</p>}<FormActions cancel={() => setDraft(null)} busy={disabled}/></form> : <div className="ds-essential-grid"><div><span><Icon name="calendar" size={16}/> When</span><strong>{dates}</strong><small>{data.dates.flexible ? 'A little flexibility, more possibilities' : data.dates.note || 'Your travel window'}</small></div><div><span>Travel party</span><strong>{data.travelers ? `${data.travelers} travelers` : 'Not set'}</strong><small>Good company, great memories</small></div><div><span>Trip budget</span><strong>{data.budget.noFixedBudget ? 'No fixed budget' : data.budget.label || 'Not set'}</strong><small>For the whole adventure</small></div></div>}
  </Card>;
}
