// Throwaway: compare three Research → Planning canvas journeys on the existing plan route.
// Every action below is simulated, with in-memory state only. No mutation API is used.
import React, { useEffect, useState } from 'react';
import './research-flow-prototype.css';

const names = { A: 'Top stepper', B: 'Journey rail', C: 'Review before canvas' };
const initialMessages = [
  { role: 'user', text: 'I’m thinking of a few days in Milan. Art, food, and a visit to San Siro.' },
  { role: 'assistant', text: 'We can group the central sights together and leave a separate afternoon for San Siro. Would you rather keep each day loose or make a day-by-day itinerary?' },
  { role: 'user', text: 'Keep it loose. Three days, with time to wander.' },
];
function Steps({ stage, onResearch, vertical = false }) {
  return <nav className={`rf-steps ${vertical ? 'vertical' : ''}`} aria-label="Plan stages"><ol><li aria-current={stage === 'research' ? 'step' : undefined}><button onClick={onResearch}><i aria-hidden="true">1</i><span>Research{vertical && <small>Explore and choose</small>}</span></button></li><li aria-current={stage !== 'research' ? 'step' : undefined}><i aria-hidden="true">2</i><span>Planning canvas{vertical && <small>Arrange and save</small>}</span></li></ol></nav>;
}
function Brief({ full = false }) {
  return <aside className="rf-brief"><div className="rf-section-label">TRIP NOTES</div><h2>Milan, at your pace</h2><dl><div><dt>Destination</dt><dd>Milan, Italy</dd></div><div><dt>Duration</dt><dd>3 days · dates open</dd></div><div><dt>Interests</dt><dd>Art, food, football</dd></div>{full && <><div><dt>Travelers</dt><dd>2 adults</dd></div><div><dt>Budget</dt><dd>Not decided</dd></div></>}</dl><p>Sample notes for this design preview.</p></aside>;
}
function Conversation({ messages, addMessage }) {
  const [input, setInput] = useState('');
  return <section className="rf-conversation" aria-label="Sample research conversation"><div className="rf-messages"><p className="rf-section-label">MILAN · RESEARCH</p>{messages.map((message, i) => <article className={`rf-message ${message.role}`} key={i}><small>{message.role === 'user' ? 'You' : 'Travella'}</small><p>{message.text}</p></article>)}</div><form className="rf-compose" onSubmit={event => { event.preventDefault(); if (input.trim()) { addMessage(input.trim()); setInput(''); } }}><label className="sr-only" htmlFor="rf-message">Preview message</label><textarea id="rf-message" rows={2} placeholder="Ask about your trip…" value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); event.currentTarget.form.requestSubmit(); } }}/><div><small>Simulated conversation</small><button className="rf-send" disabled={!input.trim()} aria-label="Send preview message">↑</button></div></form></section>;
}
function Canvas({ busy, generated, generate, back }) {
  return <section className="rf-canvas"><header><div><p className="rf-section-label">PLANNING CANVAS</p><h1>Three days in Milan</h1><p>Arrange your ideas here. Save when you’re ready.</p></div><button className="rf-primary" onClick={generate} disabled={busy || generated}>{busy ? 'Preparing draft…' : generated ? 'Draft ready' : 'Create a draft'}</button></header><p className="rf-simulation" role="status">{busy ? 'Simulating draft creation…' : generated ? 'Simulated draft ready. Nothing has been saved.' : 'Preview canvas · no real plan changes'}</p><div className="rf-canvas-grid"><section><h2>Trip details</h2><dl><div><dt>Where</dt><dd>Milan, Italy</dd></div><div><dt>When</dt><dd>3 days · dates open</dd></div><div><dt>Who</dt><dd>2 adults</dd></div></dl></section><section><h2>Places to consider</h2><p>Duomo area</p><p>Brera</p><p>San Siro</p><small>Sample ideas · not saved places</small></section><section className="rf-days"><h2>{generated ? 'A loose itinerary' : 'Room to plan'}</h2>{generated ? ['Central Milan · art and architecture', 'Brera · galleries and food', 'San Siro · check tour availability'].map((day, i) => <p key={day}><span>0{i + 1}</span>{day}</p>) : <p>Create a draft from the notes you reviewed, or keep researching.</p>}</section></div><button className="rf-text" onClick={back}>← Back to research</button></section>;
}
export function VariantA(props) {
  return <div className="rf-variant-a"><header className="rf-top"><Steps {...props}/>{props.stage === 'research' && <button className="rf-primary" onClick={props.openCanvas}>Continue to canvas <span>→</span></button>}</header>{props.stage === 'research' ? <div className="rf-research-grid"><Conversation {...props}/><Brief full/></div> : <Canvas {...props}/>}</div>;
}
export function VariantB(props) {
  return <div className="rf-variant-b"><aside className="rf-rail"><p className="rf-section-label">YOUR TRIP</p><h1>Milan</h1><Steps {...props} vertical/><Brief/></aside><div className="rf-rail-content">{props.stage === 'research' ? <><header className="rf-research-heading"><h2>Explore first.</h2><p>Keep the conversation open until you have enough to work with.</p></header><Conversation {...props}/><div className="rf-next"><div><strong>Ready to arrange your ideas?</strong><p>Your notes come with you.</p></div><button className="rf-primary" onClick={props.openCanvas}>Open canvas →</button></div></> : <Canvas {...props}/>}</div></div>;
}
export function VariantC(props) {
  return <div className="rf-variant-c"><header className="rf-top"><Steps {...props}/><span className="rf-section-label">MILAN / 3 DAYS</span></header>{props.stage === 'research' ? <div className="rf-review-layout"><Conversation {...props}/><aside className="rf-review-card"><p className="rf-section-label">BEFORE YOU PLAN</p><h2>A quick check.</h2><p>Review the trip notes before opening your canvas.</p><ul><li><span>Destination</span><strong>Milan</strong></li><li><span>Duration</span><strong>3 days</strong></li><li><span>Travelers</span><strong>2 adults</strong></li><li><span>Still open</span><strong>Dates & budget</strong></li></ul><button className="rf-primary" onClick={props.review}>Review & continue →</button><small>You can leave details undecided.</small></aside></div> : props.stage === 'review' ? <section className="rf-review-sheet"><p className="rf-section-label">RESEARCH → PLANNING CANVAS</p><h1>Take these notes into your plan?</h1><p>Open details can be decided later. Nothing is generated or saved yet.</p><Brief full/><div><button className="rf-text" onClick={props.onResearch}>Keep researching</button><button className="rf-primary" onClick={props.openCanvas}>Use these notes →</button></div></section> : <Canvas {...props}/>}</div>;
}
export function ResearchFlowPrototype({ selected }) {
  const [variant, setVariant] = useState(() => { const value = new URLSearchParams(location.search).get('variant'); return names[value] ? value : 'A'; });
  const [stage, setStage] = useState('research');
  const [messages, setMessages] = useState(initialMessages);
  const [busy, setBusy] = useState(false), [generated, setGenerated] = useState(false);
  useEffect(() => { if (!busy) return; const timer = setTimeout(() => { setGenerated(true); setBusy(false); }, 1200); return () => clearTimeout(timer); }, [busy]);
  function switchVariant(next) { const url = new URL(location.href); url.searchParams.set('variant', next); history.replaceState(null, '', url); setVariant(next); setStage('research'); setBusy(false); setGenerated(false); setMessages(initialMessages); }
  function cycle(direction) { const keys = Object.keys(names); switchVariant(keys[(keys.indexOf(variant) + direction + keys.length) % keys.length]); }
  useEffect(() => { const keydown = event => { if (event.target.closest('input,textarea,select,[contenteditable=true]')) return; if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') { event.preventDefault(); cycle(event.key === 'ArrowRight' ? 1 : -1); } }; document.addEventListener('keydown', keydown); return () => document.removeEventListener('keydown', keydown); }, [variant]);
  const props = { stage, messages, busy, generated, onResearch: () => { setStage('research'); setBusy(false); }, back: () => setStage('research'), openCanvas: () => setStage('canvas'), review: () => setStage('review'), generate: () => setBusy(true), addMessage: text => setMessages(items => [...items, { role: 'user', text }, { role: 'assistant', text: 'Preview reply: this idea stays in the conversation until you choose to add it to the plan.' }]) };
  const Variant = { A: VariantA, B: VariantB, C: VariantC }[variant];
  return <main className="research-flow-prototype" id="conversation-main"><div className="rf-preview-banner"><span>DESIGN PREVIEW · {selected?.title || 'Your plan'}</span><span>Sample trip · all actions simulated</span></div><Variant {...props}/><div className="rf-prototype-bottom"><details className="rf-state"><summary>Preview state · {stage}{busy ? ' · preparing' : ''}</summary><pre>{JSON.stringify({ variant, stage, sampleTrip: 'Milan', messages: messages.length, generation: busy ? 'simulating' : generated ? 'ready' : 'not started', persisted: false }, null, 2)}</pre></details><nav className="rf-switcher" aria-label="Design alternatives"><button onClick={() => cycle(-1)} aria-label="Previous alternative">←</button>{Object.entries(names).map(([key, name]) => <button key={key} aria-pressed={variant === key} onClick={() => switchVariant(key)}><b>{key}</b><span>{name}</span></button>)}<button onClick={() => cycle(1)} aria-label="Next alternative">→</button></nav></div></main>;
}
