import React from 'react';

function BriefEditor({ brief, onClose, onSave, saving }) {
  const [draft, setDraft] = React.useState(brief || { interests: '', start_date: '', end_date: '', travelers: 1, budget: '', transport_tolerance: '', accessibility_needs: '' });
  const update = (key, value) => setDraft(current => ({ ...current, [key]: value }));
  return <section className="brief-editor" role="dialog" aria-label="Planning Brief"><div className="drawer-header"><div><p className="eyebrow">PLANNING BRIEF</p><h2>Trip details</h2></div><button onClick={onClose} disabled={saving}>Close</button></div><div className="brief-fields"><label>Interests<textarea value={draft.interests} onChange={e => update('interests', e.target.value)} placeholder="Food, museums, beaches…" /></label><div className="brief-field-row"><label>Start date<input type="date" value={draft.start_date} onChange={e => update('start_date', e.target.value)} /></label><label>End date<input type="date" value={draft.end_date} onChange={e => update('end_date', e.target.value)} /></label></div><div className="brief-field-row"><label>Travelers<input type="number" min="1" max="50" value={draft.travelers} onChange={e => update('travelers', Number(e.target.value))} /></label><label>Budget<input value={draft.budget} onChange={e => update('budget', e.target.value)} placeholder="e.g. €2,000" /></label></div><label>Transport tolerance<input value={draft.transport_tolerance} onChange={e => update('transport_tolerance', e.target.value)} placeholder="e.g. Walkable, short transfers" /></label><label>Accessibility needs<textarea value={draft.accessibility_needs} onChange={e => update('accessibility_needs', e.target.value)} placeholder="Anything providers should accommodate" /></label></div><div className="plan-actions"><button onClick={onClose} disabled={saving}>Cancel</button><button className="primary" onClick={() => onSave(draft)} disabled={saving}>{saving ? 'Saving…' : 'Save brief'}</button></div></section>;
}

export function PlanWorkspace({ selected, actions, onOpenConversation, destinationView, setDestinationView, mapCanvas, placeSearch, mapsApiKey, mapsStatus, candidate, setCandidate, savedDestinations, saveCandidate, savingDestination, removeDestination, brief, briefOpen, setBriefOpen, onSaveBrief, briefSaving }) {
  if (selected.lifecycle === 'deleted') return <section className="plan-panel"><span className="plan-badge">Draft plan</span><h2>This plan is in Recently deleted</h2><p>Restore before {new Date(selected.recovery_deadline).toLocaleString()}</p>{actions(selected)}</section>;
  return <section className="workspace tw-workspace mx-auto w-full max-w-6xl gap-6" aria-label="Plan workspace">
    <section className="workspace-summary tw-summary rounded-2xl"><div><span className="plan-badge">Draft plan</span><p className="workspace-title">{selected.title}</p><p>Build a clear brief before you search. Your saved destinations will appear here.</p><h3 className="sr-only">Your draft is saved</h3></div><div className="plan-actions">{actions(selected)}<button className="primary" onClick={onOpenConversation}>Open conversation</button></div></section>
    <div className="workspace-toolbar"><div><p className="eyebrow">PLANNING CANVAS</p><h2>Destinations</h2></div><div className="view-toggle" role="group" aria-label="Destination view"><button className={destinationView === 'map' ? 'selected' : ''} aria-pressed={destinationView === 'map'} onClick={() => setDestinationView('map')}>Map</button><button className={destinationView === 'list' ? 'selected' : ''} aria-pressed={destinationView === 'list'} onClick={() => setDestinationView('list')}>List</button></div></div>
    {destinationView === 'map' ? <div className="map-stage" role="region" aria-label="Destination map"><div className="google-map-canvas" ref={mapCanvas} aria-hidden="true" />{!mapsApiKey && <div className="map-setup"><span className="map-kicker">MAP SETUP</span><h3>Google Maps is not configured</h3><p>Add <code>VITE_GOOGLE_MAPS_API_KEY</code> to <code>frontend/.env.local</code>, then restart the frontend.</p><small>Use a browser key restricted to this site's origins and the Maps APIs you enable.</small></div>}{mapsApiKey && <><div className="map-search" ref={placeSearch} aria-label="Destination search"><label className="sr-only" htmlFor="destination-search">Search city or country</label><input id="destination-search" type="search" placeholder="Search city or country" autoComplete="off" /><span className="sr-only">Search helpers: enter a city or country, then choose a suggestion.</span></div>{candidate && <div className="candidate-confirm"><span className="map-kicker">CANDIDATE</span><strong>{candidate.name}</strong><span>{candidate.address}</span><div><button className="primary" disabled={savingDestination} onClick={saveCandidate}>{savingDestination ? 'Saving…' : 'Save destination'}</button><button disabled={savingDestination} onClick={() => setCandidate(null)}>Dismiss</button></div></div>}{!candidate && !savedDestinations.length && <div className="map-copy"><span className="map-kicker">GOOGLE MAPS</span><h3>Find a city or country</h3><p>Search above or click the map to preview a candidate, then save it explicitly.</p>{mapsStatus && <small role="status">{mapsStatus}</small>}</div>}</>}</div> : <div className="destination-list">{savedDestinations.length ? <><p className="eyebrow">SAVED DESTINATIONS</p><ul className="saved-destination-list">{savedDestinations.map(destination => <li key={destination.place_id}><div><strong>{destination.name}</strong><span>{destination.address}</span></div><button onClick={() => removeDestination(destination)}>Remove</button></li>)}</ul></> : <><div className="empty-icon" aria-hidden="true">＋</div><h3>No destinations saved</h3><p>Search for a city or country and save it as a candidate pin.</p><button className="primary" onClick={() => setDestinationView('map')}>Find a destination</button></>}</div>}
    <div className="workspace-lower"><section className="brief-card"><div><p className="eyebrow">PLANNING BRIEF</p><h2>{brief?.interests || brief?.start_date ? `${brief.travelers} traveler${brief.travelers === 1 ? '' : 's'}` : 'Still to decide'}</h2></div><p>{brief?.interests || 'Dates, travelers, budget, and interests will live here. You can edit confirmed details directly.'}</p><button onClick={() => setBriefOpen(true)}>Open brief</button></section><section className="conversation-card"><p className="eyebrow">CONVERSATION</p><h2>Ready when you are</h2><p>The conversation panel is available as a placeholder while agent planning is being built.</p><button>Open panel</button></section></div>
  {briefOpen && <BriefEditor brief={brief} onClose={() => setBriefOpen(false)} onSave={onSaveBrief} saving={briefSaving} />}
  </section>;
}
