import React from 'react';

export function PlanWorkspace({ selected, actions, onOpenConversation, destinationView, setDestinationView, mapCanvas, placeSearch, mapsApiKey, mapsStatus, candidate, setCandidate, savedDestinations, saveCandidate, savingDestination, removeDestination }) {
  if (selected.lifecycle === 'deleted') return <section className="plan-panel"><span className="plan-badge">Draft plan</span><h2>This plan is in Recently deleted</h2><p>Restore before {new Date(selected.recovery_deadline).toLocaleString()}</p>{actions(selected)}</section>;
  return <section className="workspace tw-workspace mx-auto w-full max-w-6xl gap-6" aria-label="Plan workspace">
    <h3 className="sr-only">Your draft is saved</h3>

    <div className="workspace-toolbar"><div><p className="eyebrow">PLANNING CANVAS</p><h2>Destinations</h2></div><div className="view-toggle" role="group" aria-label="Destination view"><button className={destinationView === 'map' ? 'selected' : ''} aria-pressed={destinationView === 'map'} onClick={() => setDestinationView('map')}>Map</button><button className={destinationView === 'list' ? 'selected' : ''} aria-pressed={destinationView === 'list'} onClick={() => setDestinationView('list')}>List</button></div></div>
    {destinationView === 'map' ? <div className="map-stage" role="region" aria-label="Destination map"><div className="google-map-canvas" ref={mapCanvas} aria-hidden="true" />{!mapsApiKey && <div className="map-setup"><span className="map-kicker">MAP SETUP</span><h3>Google Maps is not configured</h3><p>Add <code>VITE_GOOGLE_MAPS_API_KEY</code> to <code>frontend/.env.local</code>, then restart the frontend.</p><small>Use a browser key restricted to this site's origins and the Maps APIs you enable.</small></div>}{mapsApiKey && <><div className="map-search" ref={placeSearch} aria-label="Destination search"><label className="sr-only" htmlFor="destination-search">Search city or country</label><input id="destination-search" type="search" placeholder="Search city or country" autoComplete="off" /><span className="sr-only">Search helpers: enter a city or country, then choose a suggestion.</span></div>{candidate && <div className="candidate-confirm"><span className="map-kicker">CANDIDATE</span><strong>{candidate.name}</strong><span>{candidate.address}</span><div><button className="primary" disabled={savingDestination} onClick={saveCandidate}>{savingDestination ? 'Saving…' : 'Save destination'}</button><button disabled={savingDestination} onClick={() => setCandidate(null)}>Dismiss</button></div></div>}{!candidate && !savedDestinations.length && <div className="map-copy"><span className="map-kicker">GOOGLE MAPS</span><h3>Find a city or country</h3><p>Search above or click the map to preview a candidate, then save it explicitly.</p>{mapsStatus && <small role="status">{mapsStatus}</small>}</div>}</>}</div> : <div className="destination-list">{savedDestinations.length ? <><p className="eyebrow">SAVED DESTINATIONS</p><ul className="saved-destination-list">{savedDestinations.map(destination => <li key={destination.place_id}><div><strong>{destination.name}</strong><span>{destination.address}</span></div><button onClick={() => removeDestination(destination)}>Remove</button></li>)}</ul></> : <><div className="empty-icon" aria-hidden="true">＋</div><h3>No destinations saved</h3><p>Search for a city or country and save it as a candidate pin.</p><button className="primary" onClick={() => setDestinationView('map')}>Find a destination</button></>}</div>}

  </section>;
}
